name: "Run neophile"
description: >-
  This composite action installs and runs neophile. It includes Python setup,
  but does not cache the neophile installation.
inputs:
  app-id:
    description: "GitHub App id to run as (required for pr)"
    required: false
    default: ""
  app-secret:
    description: "GitHub App secret to use (required for pr)"
    required: false
    default: ""
  python-version:
    description: "Python version"
    required: true
  mode:
    description: "Mode of operation (one of check, update, or pr)"
    required: true
  types:
    description: >-
      Space-separated types of dependencies to check (omit to check all)
    required: false
    default: ""
  working-directory:
    description: "Directory in which to run neophile"
    required: true
    default: "."

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install neophile
      shell: bash
      run: python -m pip install --upgrade neophile

    - name: Run neophile check
      if: inputs.mode == 'check'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: neophile check ${{ inputs.types }}

    - name: Run neophile update
      if: inputs.mode == 'update'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: neophile update ${{ inputs.types }}

    - name: Run neophile update --pr
      if: inputs.mode == 'pr'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: neophile update --pr ${{ inputs.types }}
      env:
        NEOPHILE_GITHUB_APP_ID: ${{ inputs.app-id }}
        NEOPHILE_GITHUB_PRIVATE_KEY: ${{ inputs.app-secret }}
